/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package kr.ac.snu.ids;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int TABLE = 9;
  /** RegularExpression Id. */
  int CREATE = 10;
  /** RegularExpression Id. */
  int DROP = 11;
  /** RegularExpression Id. */
  int DESC = 12;
  /** RegularExpression Id. */
  int SHOW = 13;
  /** RegularExpression Id. */
  int TABLES = 14;
  /** RegularExpression Id. */
  int INSERT = 15;
  /** RegularExpression Id. */
  int INTO = 16;
  /** RegularExpression Id. */
  int DELETE = 17;
  /** RegularExpression Id. */
  int SELECT = 18;
  /** RegularExpression Id. */
  int FROM = 19;
  /** RegularExpression Id. */
  int WHERE = 20;
  /** RegularExpression Id. */
  int AS = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int IS = 24;
  /** RegularExpression Id. */
  int NOT = 25;
  /** RegularExpression Id. */
  int KEY = 26;
  /** RegularExpression Id. */
  int PRIMARY = 27;
  /** RegularExpression Id. */
  int FOREIGN = 28;
  /** RegularExpression Id. */
  int REFERENCES = 29;
  /** RegularExpression Id. */
  int VALUES = 30;
  /** RegularExpression Id. */
  int NOT_NULL = 31;
  /** RegularExpression Id. */
  int NULL = 32;
  /** RegularExpression Id. */
  int ASTERISK = 33;
  /** RegularExpression Id. */
  int PERIOD = 34;
  /** RegularExpression Id. */
  int INEQ_S = 35;
  /** RegularExpression Id. */
  int INEQ_B = 36;
  /** RegularExpression Id. */
  int INEQ_SE = 37;
  /** RegularExpression Id. */
  int INEQ_BE = 38;
  /** RegularExpression Id. */
  int INEQ_E = 39;
  /** RegularExpression Id. */
  int INEQ_NE = 40;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 41;
  /** RegularExpression Id. */
  int SEMICOLON = 42;
  /** RegularExpression Id. */
  int LEFT_PAREN = 43;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 44;
  /** RegularExpression Id. */
  int COMMA = 45;
  /** RegularExpression Id. */
  int UNDERSCORE = 46;
  /** RegularExpression Id. */
  int INT_VALUE = 47;
  /** RegularExpression Id. */
  int DATE_VALUE = 48;
  /** RegularExpression Id. */
  int CHAR_STRING = 49;
  /** RegularExpression Id. */
  int QUOTE = 50;
  /** RegularExpression Id. */
  int SIGN = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 53;
  /** RegularExpression Id. */
  int ALPHABET = 54;
  /** RegularExpression Id. */
  int NNNN = 55;
  /** RegularExpression Id. */
  int NN = 56;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 57;
  /** RegularExpression Id. */
  int NEWLINE = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"table\"",
    "\"create\"",
    "\"drop\"",
    "\"desc\"",
    "\"show\"",
    "\"tables\"",
    "\"insert\"",
    "\"into\"",
    "\"delete\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"as\"",
    "\"or\"",
    "\"and\"",
    "\"is\"",
    "\"not\"",
    "\"key\"",
    "\"primary\"",
    "\"foreign\"",
    "\"references\"",
    "\"values\"",
    "\"not null\"",
    "\"null\"",
    "\"*\"",
    "\".\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<CHAR_STRING>",
    "\"\\\'\"",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<NNNN>",
    "<NN>",
    "<NON_QUOTE_CHARACTER>",
    "<NEWLINE>",
  };

}
