/* Generated By:JavaCC: Do not edit this line. SimpleDBMSParserConstants.java */
package main.java.kr.ac.snu.ids;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleDBMSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int EXIT = 5;
  /** RegularExpression Id. */
  int INT = 6;
  /** RegularExpression Id. */
  int CHAR = 7;
  /** RegularExpression Id. */
  int DATE = 8;
  /** RegularExpression Id. */
  int CREATE_TABLE = 9;
  /** RegularExpression Id. */
  int DROP_TABLE = 10;
  /** RegularExpression Id. */
  int DESC = 11;
  /** RegularExpression Id. */
  int SHOW_TABLES = 12;
  /** RegularExpression Id. */
  int INSERT_INTO = 13;
  /** RegularExpression Id. */
  int DELETE_FROM = 14;
  /** RegularExpression Id. */
  int SELECT = 15;
  /** RegularExpression Id. */
  int FROM = 16;
  /** RegularExpression Id. */
  int WHERE = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int IS = 21;
  /** RegularExpression Id. */
  int NOT = 22;
  /** RegularExpression Id. */
  int PRIMARY_KEY = 23;
  /** RegularExpression Id. */
  int FOREIGN_KEY = 24;
  /** RegularExpression Id. */
  int REFERENCES = 25;
  /** RegularExpression Id. */
  int VALUES = 26;
  /** RegularExpression Id. */
  int NOT_NULL = 27;
  /** RegularExpression Id. */
  int NULL = 28;
  /** RegularExpression Id. */
  int ASTERISK = 29;
  /** RegularExpression Id. */
  int PERIOD = 30;
  /** RegularExpression Id. */
  int INEQ_S = 31;
  /** RegularExpression Id. */
  int INEQ_B = 32;
  /** RegularExpression Id. */
  int INEQ_SE = 33;
  /** RegularExpression Id. */
  int INEQ_BE = 34;
  /** RegularExpression Id. */
  int INEQ_E = 35;
  /** RegularExpression Id. */
  int INEQ_NE = 36;
  /** RegularExpression Id. */
  int SEMICOLON = 37;
  /** RegularExpression Id. */
  int LEFT_PAREN = 38;
  /** RegularExpression Id. */
  int RIGHT_PAREN = 39;
  /** RegularExpression Id. */
  int COMMA = 40;
  /** RegularExpression Id. */
  int UNDERSCORE = 41;
  /** RegularExpression Id. */
  int INT_VALUE = 42;
  /** RegularExpression Id. */
  int DATE_VALUE = 43;
  /** RegularExpression Id. */
  int CHAR_STRING = 44;
  /** RegularExpression Id. */
  int QUOTE = 45;
  /** RegularExpression Id. */
  int SIGN = 46;
  /** RegularExpression Id. */
  int DIGIT = 47;
  /** RegularExpression Id. */
  int LEGAL_IDENTIFIER = 48;
  /** RegularExpression Id. */
  int ALPHABET = 49;
  /** RegularExpression Id. */
  int NNNN = 50;
  /** RegularExpression Id. */
  int NN = 51;
  /** RegularExpression Id. */
  int NON_QUOTE_CHARACTER = 52;
  /** RegularExpression Id. */
  int NON_QUOTE_SPECIAL_CHARACTERS = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"exit\"",
    "\"int\"",
    "\"char\"",
    "\"date\"",
    "\"create table\"",
    "\"drop table\"",
    "\"desc\"",
    "\"show tables\"",
    "\"insert into\"",
    "\"delete from\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"as\"",
    "\"or\"",
    "\"and\"",
    "\"is\"",
    "\"not\"",
    "\"primary key\"",
    "\"foreign key\"",
    "\"references\"",
    "\"values\"",
    "\"not null\"",
    "\"null\"",
    "\"*\"",
    "\".\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"_\"",
    "<INT_VALUE>",
    "<DATE_VALUE>",
    "<CHAR_STRING>",
    "\"\\\'\"",
    "<SIGN>",
    "<DIGIT>",
    "<LEGAL_IDENTIFIER>",
    "<ALPHABET>",
    "<NNNN>",
    "<NN>",
    "<NON_QUOTE_CHARACTER>",
    "<NON_QUOTE_SPECIAL_CHARACTERS>",
  };

}
